# Generated by Django 5.2.1 on 2025-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_groups_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_owner",
            field=models.BooleanField(
                default=False, verbose_name="Владелец материалов"
            ),
        ),
    ]
