# Generated by Django 5.2.1 on 2025-05-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Варианты ответа"),
                    ("open_ended", "Открытый вопрос"),
                ],
                default="multiple_choice",
                max_length=20,
            ),
        ),
    ]
