# Generated by Django 5.2.1 on 2025-05-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_question_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
