# Generated by Django 5.2.1 on 2025-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_testresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_answer",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer_open_ended",
            field=models.CharField(
                blank=True,
                help_text="Правильный ответ для открытого вопроса.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_choice_answer",
            field=models.IntegerField(
                blank=True,
                help_text="Индекс правильного ответа для закрытого вопроса (варианты ответа).",
                null=True,
            ),
        ),
    ]
