# Generated by Django 5.2.1 on 2025-05-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0007_remove_question_correct_answer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="answer_text",
        ),
        migrations.AddField(
            model_name="answer",
            name="correct_answer_open_ended",
            field=models.CharField(
                blank=True,
                help_text="Правильный ответ для открытого вопроса.",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="correct_choice_answer",
            field=models.IntegerField(
                blank=True,
                help_text="Индекс правильного ответа для закрытого вопроса (варианты ответа).",
                null=True,
            ),
        ),
    ]
