# Generated by Django 5.2.1 on 2025-05-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0008_remove_answer_answer_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="correct_answer_open_ended",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="correct_choice_answer",
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_text",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
