# Generated by Django 5.2.1 on 2025-05-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0009_remove_answer_correct_answer_open_ended_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="correct_answer_open_ended",
        ),
        migrations.RemoveField(
            model_name="question",
            name="correct_choice_answer",
        ),
        migrations.AddField(
            model_name="question",
            name="correct_answer",
            field=models.JSONField(
                blank=True,
                help_text="Правильный ответ (может быть текстом или числом).",
                null=True,
            ),
        ),
    ]
