# Generated by Django 5.2.1 on 2025-05-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0011_theme_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="material",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["created_at"]},
        ),
    ]
