# Generated by Django 5.2.1 on 2025-05-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0012_alter_material_options_alter_review_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="theme",
            options={"ordering": ["title"]},
        ),
    ]
